### PR TITLE
Merge Dev to Master

### PR DESCRIPTION
**Pull request by mehervishnu**
the project is stable enough, we can now push to master

### CODE REVIEW

**Comment by mehervishnu** [comment]
after fixing calendar view design errors then we can proceed.

**Review by akhildama — APPROVED** [review]
design issues are all completed from my side, I think we can proceed with the merge

**Review by naveenbillapati — APPROVED** [review]
i just pushed my code which resolved the user accounts problem, we can proceed with the merge.

**Review by irjreddy — APPROVED** [review]
i just pushed the signout feature as well, all good from my side

**Pull request merged**
